version: '3'
services:
  fp-view:
    build: .
    ports:
      - 3000:80
    environment:
      API_HOST: fp-api
    links:
      - fp-api
  fp-api:
    build: ../fp-api
    environment:
      DB_HOST: mongodb
    links:
      - mongodb
    volumes:
      - facultyprofilesfiles:/fp-files
  mongo-seed:
    build: ../fp-api/mongo-seed
    restart: on-failure
    volumes:
      - facultyprofilesfiles:/fp-files
    links:
      - mongodb
    depends_on:
      - fp-view
  mongodb:
    image: mongo:latest
    volumes:
      - facultyprofilesdb:/data/db
volumes:
  facultyprofilesdb: {}
  facultyprofilesfiles: {}
